class_name RockShell
extends RefCounted
## A lump of rock, generated from a seed. One shape, shared by everything in this world that is
## a rock: the Engineer's barricade underground and the boulders lying about the lawn.
##
## SHARED BECAUSE THEY ARE THE SAME OBJECT, not to save typing. A barricade is a rock a mouse
## heaved into a gap and a boulder is a rock that was already there; if they were generated by
## two functions they would drift apart, and the moment they look like different materials the
## player has to learn twice that a Brute is what shifts rock.
##
## GENERATED RATHER THAN IMPORTED, like the tunnel chunks and for the same reason: the shape is
## still under test, and changing it should be editing a constant and pressing play. It also
## means every rock in the match is a different rock for free, which a single imported mesh
## could only fake by rotating.
##
## SEEDED BY ITS PLACE IN THE WORLD, by the caller. The same cell always grows the same rock, two
## neighbours are visibly different, and a screenshot is comparable to the last one.

## Latitude and longitude bands. Low, deliberately: this is a lump of rock at isometric distance,
## and the facets are the look.
const RINGS: int = 7
const SEGMENTS: int = 12
## How far each vertex's radius may stray, before smoothing.
const WOBBLE: float = 0.30


## A boulder `span` across and `tall` high, sitting ON the ground rather than centred in it --
## a rock half sunk into the floor is a rock you can walk through the top of.
##
## The lattice of radii is jittered and then smoothed against its neighbours, which is the whole
## trick. Jitter alone gives a sea urchin, because every vertex is independent of the ones beside
## it; one averaging pass turns the spikes into the lobes a boulder actually has.
static func build(span: float, tall: float, seed_value: int) -> ArrayMesh:
	var rng := RandomNumberGenerator.new()
	rng.seed = seed_value

	var radii: Array[float] = []
	for ring in range(RINGS + 1):
		for segment in range(SEGMENTS):
			radii.append(1.0 + rng.randf_range(-WOBBLE, WOBBLE))
	var smooth: Array[float] = []
	for ring in range(RINGS + 1):
		for segment in range(SEGMENTS):
			var here := _radius(radii, ring, segment)
			var around := (
				_radius(radii, ring, segment - 1) + _radius(radii, ring, segment + 1)
				+ _radius(radii, ring - 1, segment) + _radius(radii, ring + 1, segment)
			)
			smooth.append((here * 2.0 + around) * 0.1667)

	var t := SurfaceTool.new()
	t.begin(Mesh.PRIMITIVE_TRIANGLES)
	for ring in range(RINGS):
		for segment in range(SEGMENTS):
			var a := _point(smooth, ring, segment, span, tall)
			var b := _point(smooth, ring, segment + 1, span, tall)
			var c := _point(smooth, ring + 1, segment + 1, span, tall)
			var d := _point(smooth, ring + 1, segment, span, tall)
			for vertex: Vector3 in [a, b, c, a, c, d]:
				t.add_vertex(vertex)
	t.generate_normals()
	return t.commit()


## The material a rock is drawn with. Here rather than at each call site so a barricade and a
## boulder cannot end up different kinds of stone by an edit to one file.
static func material_for(colour: Color) -> StandardMaterial3D:
	var material := StandardMaterial3D.new()
	material.albedo_color = colour
	material.roughness = 0.95
	# The same grain as the seams it was cut from, so a rock reads as a piece of this map rather
	# than as a prop dropped into it.
	DirtTexture.apply_to(material)
	return material


static func _radius(radii: Array[float], ring: int, segment: int) -> float:
	var r := clampi(ring, 0, RINGS)
	# Longitude wraps; latitude clamps. Wrapping latitude too would join the north pole to the
	# south and put a crease across the middle of every rock.
	return radii[r * SEGMENTS + posmod(segment, SEGMENTS)]


static func _point(
	radii: Array[float], ring: int, segment: int, span: float, tall: float
) -> Vector3:
	var scaled := _radius(radii, ring, segment)
	var phi := PI * float(ring) / float(RINGS)
	var theta := TAU * float(segment) / float(SEGMENTS)
	return Vector3(
		sin(phi) * cos(theta) * span * scaled,
		tall * 0.5 * (1.0 - cos(phi) * scaled),
		sin(phi) * sin(theta) * span * scaled
	)
